### ISSUE TITLE
No matter the file it shows "Unable to access service resolver"

### ISSUE THREAD

**Issue by sahadevansandeep** [valtech/aem-virus-scan#10]
Hi 

I am getting "Unable to access service resolver" no matter the file i choose to upload. I tried images, pdf and even blank text files.

I am using Macos big sur. with AEM 6.5.9 and AEM virus scan 1.1.1

My friend tried in windows as well he also faced the same error

![image](https://user-images.githubusercontent.com/95322084/144171097-00321114-5655-4cda-9921-fbeb117c93b0.png)

PS the bundles are active
![image](https://user-images.githubusercontent.com/95322084/144168416-b2d31295-f609-4cf8-9263-723d3994fdd2.png)

**Comment by PuneethBSMys** [comment]
Getting the same error for Windows.
AEM 6.5.9
AEM Virus scan - 1.1.1
clamav - clamav-0.104.1.win.x64

Do we need any changes in the clamd.conf file? Attached the conf file used in Windows
[clamd.conf.txt](https://github.com/valtech/aem-virus-scan/files/7629915/clamd.conf.txt)
.
Thanks,

**Comment by gruberrolandvaltech** [comment]
Can you retry with version 2.0.0?

**Comment by sahadevansandeep** [comment]
In 2.0.0 the malicious test files from https://github.com/fire1ce/eicar-standard-antivirus-test-files are not getting detected. 
![image](https://user-images.githubusercontent.com/95322084/144971441-a7a73462-3f7c-48c5-bf3a-c4f7a9d04683.png)

**Comment by gruberrolandvaltech** [comment]
What do you get on this URL on AEM?

/libs/granite/operations/content/healthreports/healthreport.avsHealthCheckmBean.html/system/sling/monitoring/mbeans/org/apache/sling/healthcheck/HealthCheck/avsSelfCheckHCmBean

**Comment by gruberrolandvaltech** [comment]
Also, use the "eicar.com" file for testing. I think one of the other files is not detected by ClamAV.

**Comment by sahadevansandeep** [comment]
we were able to create a file and test which worked fine. I have another issue but i will raise a separate thread on that. 

PS - The link to 'release-section' in readme section is pointing to wrong page https://github.com/valtech/aem-easy-content-upgrade/releases instead of https://github.com/valtech/aem-virus-scan/releases

This issue can be closed. Thanks for the support.

**Comment by gruberrolandvaltech** [comment]
Thanks for the hint with the links, fixed now. :)
