### ISSUE TITLE
ClamAV AVS service

### ISSUE THREAD

**Issue by sahadevansandeep** [valtech/aem-virus-scan#12]
Hi

I am trying to reuse the AVSService methods to scan the documents in my custom application. 

After i start the clam AV , I try to scan a document from my custom application by invoking the avsService.scan() method, however I am getting isclean as 'true' even for a file with virus. Same file is getting detected with virus when i try the 'Scan a file' option in AEM tools.

**Comment by gruberrolandvaltech** [comment]
Maybe there is an issue building the input stream in your custom code. Could it be that it is already read or stream is closed? Can you post some lines how it is created?
The AEM tool uses the exact same method of AVSService.

**Comment by sahadevansandeep** [comment]
Yes my bad i read the stream before sending it. thanks for your support.
