### ISSUE TITLE
ERROR: Can't parse clamd configuration file C:\Users\rc30387\clamav-0.103.2-win-x64-portable\clamd.conf

### ISSUE THREAD

**Issue by brandongoldman** [valtech/aem-virus-scan#8]
Hello @gruberrolandvaltech!
 
I tried using clamav-0.103.2-win-x64-portable as per suggestion. This is in my location:
 
`C:\Users\rc30387\clamav-0.103.2-win-x64-portable
`
In the clam scan command I am using `C:\Users\rc30387\clamav-0.103.2-win-x64-portable\clamdscan --infected --no-summary`
 
I am getting the following error  for all assets I upload:
 
The scanner reported a virus
```
Result:
ERROR: Can't parse clamd configuration file C:\Users\rc30387\clamav-0.103.2-win-x64-portable\clamd.conf
```
 
Can you please advice any solution to this if clamav needs to be upgraded/downgraded or anything else?
 
Thanks!

**Comment by gruberrolandvaltech** [comment]
Looks like the clamd config is corrupt or missing. Check if  C:\Users\rc30387\clamav-0.103.2-win-x64-portable\clamd.conf exists at all.
You can also try to run clamdscan from shell: C:\Users\rc30387\clamav-0.103.2-win-x64-portable\clamdscan SOMETEST.FILE

**Comment by brandongoldman** [comment]
hello @gruberrolandvaltech  I am now able to use the Virus scan on my AEM instance :)

In my  `Tools > AEM Virus Scan`  I do get the scan report when I choose and upload a file.

However, I am not able to the Scan on assets uploaded to DAM. It just uploads the document without scanning it. Any idea if there is another plugin/configurations that needs to be done to achieve this?

**Comment by gruberrolandvaltech** [comment]
Did you configure POST filter?

https://github.com/valtech/aem-virus-scan#configuration

**Comment by brandongoldman** [comment]
Yes @gruberrolandvaltech we have configured the AVS Post filter configurations:
 
```
url includes pattern  "[/content/dam/.*]"
url excludes pattern "[]"
```
 
Still, the assets we upload in DAM are not scanned.

**Comment by gruberrolandvaltech** [comment]
What is your AEM version and service pack?
Did you try to upload the eicar test virus? Only infected files will show up in the history.

In /system/console/services do you see something like this?
<img width="1297" alt="grafik" src="https://user-images.githubusercontent.com/39398496/119774585-abc9e400-bec2-11eb-8dea-562374b0a10d.png">

**Comment by gruberrolandvaltech** [comment]
Please also make sure that you use the latest version. There was an issue in the past when no email configuration was done.

**Comment by RajCarvalho** [comment]
@gruberrolandvaltech my AEM version is 6.5.0 with no service pack will that work?

**Comment by gruberrolandvaltech** [comment]
Please update to AEM 6.5.8 and AEM Virus Scan 1.1.0.

**Comment by RajCarvalho** [comment]
hey @gruberrolandvaltech I did the upgrade  to AEM 6.5.8 and AEM Virus Scan 1.1.0. still I am not able to scan assets automatically when we try to upload them on a particular folder in DAM.


I am attaching the config below not able to understand Y I am not able to scan dam uploads 
![AVSConfig](https://user-images.githubusercontent.com/25556648/120509508-2f397880-c38e-11eb-97e1-8a5960c56c87.PNG)

**Comment by RajCarvalho** [comment]
it works when I use the window to scan 
![AEMscan-window](https://user-images.githubusercontent.com/25556648/120556455-22cf1300-c3c2-11eb-8311-49a4c0744522.PNG)

but when we try through dam it directly uploads without scanning
![Virus](https://user-images.githubusercontent.com/25556648/120556585-501bc100-c3c2-11eb-8b79-ac0e8497f99a.PNG)

**Comment by gruberrolandvaltech** [comment]
There will be no extra message in DAM when no virus was detected. You need to upload a sample virus to check if virus uploads are blocked. Use the eicar test files for that:
https://www.eicar.org/?page_id=3950
